--- #YAML:1.0
name:                     Data-Phrasebook-Loader-XML
version:                  0.16
abstract:                 Loader class for phrasebook implementations using XML files.
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Carp:                   0
  Data::Phrasebook:       0.24
  IO::File:               0
  XML::Parser:            0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  Test::More:             0.70

provides:
  Data::Phrasebook::Loader::XML:
    file:     lib/Data/Phrasebook/Loader/XML.pm
    version:  0.16
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Phrasebook-Loader-XML
  repository: http://github.com/barbie/data-phrasebook-loader-xml

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
